import Image from "next/image"
import Link from "next/link"
import heroImg from '/public/imgs/hero.jpg'

export default async function HeroSection () {



    return (
        <div className="w-full h-[calc(100vh-80px)]">
            <div className="w-full h-full">
                <Image alt="" className="object-cover" src={heroImg} fill={true}/>
            </div>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1><h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
            <h1>AAAAA</h1>
        </div>
    )
}